export const AUTH_APP = 'AUTH_APP'
export const CLIENT_ID = 'VyapakKh-Kilobyte-PRD-d7f402c32-f5a9a05c'
export const CLIENT_SECRET = 'PRD-7f402c320665-fdaa-43c2-b92d-a837'
export const B64CREDENTIALS = 'Basic' + " " + "VnlhcGFrS2gtS2lsb2J5dGUtUFJELWQ3ZjQwMmMzMi1mNWE5YTA1YzpQUkQtN2Y0MDJjMzIwNjY1LWZkYWEtNDNjMi1iOTJkLWE4Mzc="
export const AUTH_TOKEN = 'AUTH_TOKEN'
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELIVER_AT = 'DELIVER_AT'
export const CHECK_OUT = 'CHECK_OUT'
export const REMOVE_ITEM = 'REMOVE_ITEM'